<?xml version="1.0" encoding="UTF-8"?><testrun name="ua.con.fielden.tests" project="SearchAlgorythms" tests="19" started="19" failures="0" errors="2" ignored="0">
  <testsuite name="ua.con.fielden.tests.TestGraph" time="0.022">
    <testcase name="graph_created_by_builder_should_be_equal_to_hand_createg_graph" classname="ua.con.fielden.tests.TestGraph" time="0.015"/>
    <testcase name="adjacency_list_should_be_create_correctly" classname="ua.con.fielden.tests.TestGraph" time="0.002"/>
    <testcase name="list_of_edges_of_vertex_should_be_create_correct" classname="ua.con.fielden.tests.TestGraph" time="0.002"/>
    <testcase name="graph_should_not_have_edges_with_verteces_wich_donot_exist_in_setOfVertex" classname="ua.con.fielden.tests.TestGraph" time="0.0"/>
    <testcase name="graph_should_not_have_null_set_of_verteces" classname="ua.con.fielden.tests.TestGraph" time="0.003"/>
  </testsuite>
  <testsuite name="ua.con.fielden.tests.TestVertex" time="0.009">
    <testcase name="the_same_vertexes_shoul_be_equal" classname="ua.con.fielden.tests.TestVertex" time="0.001"/>
    <testcase name="different_verteces_should_have_different_hashCodes" classname="ua.con.fielden.tests.TestVertex" time="0.008"/>
  </testsuite>
  <testsuite name="ua.con.fielden.tests.TestBfs" time="0.012">
    <testcase name="Bfs_should_work_as_expected" classname="ua.con.fielden.tests.TestBfs" time="0.009"/>
    <testcase name="Bfs_should_work_correctly" classname="ua.con.fielden.tests.TestBfs" time="0.003"/>
  </testsuite>
  <testsuite name="ua.con.fielden.tests.TestEdge" time="0.004">
    <testcase name="it_should_be_impossible_to_create_edges_with_null_vertexes" classname="ua.con.fielden.tests.TestEdge" time="0.001"/>
    <testcase name="the_same_edge_should_be_equal" classname="ua.con.fielden.tests.TestEdge" time="0.001"/>
    <testcase name="hashCodes_of_equal_vertexes_shoul_be_the_same" classname="ua.con.fielden.tests.TestEdge" time="0.002"/>
  </testsuite>
  <testsuite name="ua.con.fielden.tests.TestDfs" time="0.019">
    <testcase name="Dfs_should_work_as_expected" classname="ua.con.fielden.tests.TestDfs" time="0.015">
      <error>java.lang.NullPointerException
	at ua.com.fielden.graph.DeapthFirstIterator.travel(DeapthFirstIterator.java:50)
	at ua.com.fielden.graph.DeapthFirstIterator.next(DeapthFirstIterator.java:40)
	at ua.com.fielden.graph.Graph.dfs(Graph.java:80)
	at ua.con.fielden.tests.TestDfs.Dfs_should_work_as_expected(TestDfs.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</error>
    </testcase>
    <testcase name="Dfs_should_work_correctly" classname="ua.con.fielden.tests.TestDfs" time="0.003">
      <error>java.lang.NullPointerException
	at ua.com.fielden.graph.DeapthFirstIterator.travel(DeapthFirstIterator.java:50)
	at ua.com.fielden.graph.DeapthFirstIterator.next(DeapthFirstIterator.java:40)
	at ua.com.fielden.graph.Graph.dfs(Graph.java:80)
	at ua.con.fielden.tests.TestDfs.Dfs_should_work_correctly(TestDfs.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</error>
    </testcase>
  </testsuite>
  <testsuite name="ua.con.fielden.tests.TestBuilder" time="0.004">
    <testcase name="graph_cannot_be_without_any_vertexes" classname="ua.con.fielden.tests.TestBuilder" time="0.001"/>
    <testcase name="it_should_be_imposible_to_add_the_same_vertex" classname="ua.con.fielden.tests.TestBuilder" time="0.0"/>
    <testcase name="it_should_be_impossible_to_build_graph_with_edge_vertexes_of_wich_not_egzist_in_setOfVertex" classname="ua.con.fielden.tests.TestBuilder" time="0.0"/>
    <testcase name="it_should_be_impossible_to_add_edge_with_null_verteves" classname="ua.con.fielden.tests.TestBuilder" time="0.001"/>
    <testcase name="it_should_be_imposible_to_add_the_same_edge" classname="ua.con.fielden.tests.TestBuilder" time="0.001"/>
  </testsuite>
</testrun>
